using AdvancedBudgetManagerCore.model.request;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;

namespace AdvancedBudgetManagerCore.repository {
   /// <summary>
   /// Provides functionality for performing CRUD operations on the database
   /// </summary>
    public interface ICrudRepository<TCreate, TRead, TUpdate, TEntity, TKey> {
        /// <summary>
        /// Retrieves the specified data from the database.
        /// </summary>
        /// <param name="getRequest">The data request object containing the search parameter.</param>
        /// <returns>A <see cref="IEnumerable"/> collection of containing the retrieved entities.</returns>
        /// <exception cref="SystemException"></exception>
        public IEnumerable<TEntity> GetAllByCriteria(TRead getRequest);

        /// <summary>
        /// Retrieves the specified entity from the database by id.
        /// </summary>
        /// <param name="id">The id of the specified entity.</param>
        /// <returns>The entity containing the specified id.</returns>
        public TEntity GetById(TKey id);

        /// <summary>
        /// Inserts the specified data into the database.
        /// </summary>
        /// <param name="insertRequest">The DTO containing the data that need to be inserted.</param>
        /// <returns>The ID of the inserted record which was generated by the database.</returns>
        public TKey InsertData(TCreate insertRequest);

        /// <summary>
        /// Updates the specified data from the database.
        /// </summary>
        /// <param name="updateRequest">The data update request object containing the new information.</param>
        public void UpdateData(TUpdate updateRequest);

        /// <summary>
        /// Deletes the specififed dta from the database.
        /// </summary>
        /// <param name="id">The ID of the record which needs to be deleted.</param>
        public void DeleteById(TKey id);

    }
}
