using System;
using System.Collections;
using System.Collections.Generic;

namespace AdvancedBudgetManagerCore.repository {
    /// <summary>
    /// Provides functionality for performing CRUD operations on the database
    /// </summary>
    public interface ICrudRepository<TEntity, TKey> {
        /// <summary>
        /// Retrieves the entire list of entities of a specific type from the database.
        /// </summary>
        /// <returns>A <see cref="IEnumerable"/> collection of containing the retrieved entities.</returns>
        /// <exception cref="SystemException"></exception>
        public IEnumerable<TEntity> GetAll();

        /// <summary>
        /// Retrieves the specified entity from the database by id.
        /// </summary>
        /// <param name="id">The id of the specified entity.</param>
        /// <returns>The entity containing the specified id.</returns>
        public TEntity GetById(TKey id);

        /// <summary>
        /// Inserts the specified entity into the database.
        /// </summary>
        /// <param name="entity">The entity that needs to be inserted.</param>
        /// <returns>The ID of the inserted record which was generated by the database.</returns>
        public TEntity Insert(TEntity entity);

        /// <summary>
        /// Updates the specified entity from the database.
        /// </summary>
        /// <param name="entity">The entity that needs to be updated.</param>
        public TEntity Update(TEntity entity);

        /// <summary>
        /// Deletes the specified entity from the database.
        /// </summary>
        /// <param name="id">The ID of the entity that needs to be deleted.</param>
        public bool Delete(TKey id);

    }
}
