<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="resources\scripts\insert_incomes_data.sql" />
    <None Remove="resources\scripts\mysql_schema.sql" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="resources\scripts\insert_incomes_data.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="resources\scripts\mysql_schema.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.0.2" />
    <PackageReference Include="MSTest.TestFramework" Version="4.0.2" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="Testcontainers.MySql" Version="4.12.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdvancedBudgetManagerCore\AdvancedBudgetManagerCore.csproj" />
    <ProjectReference Include="..\AdvancedBudgetManagerUI\AdvancedBudgetManagerUI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
