using AdvancedBudgetManager.utils;
using AdvancedBudgetManagerCore.model.message;
using AdvancedBudgetManagerCore.utils.security;
using AdvancedBudgetManagerCore.view_model;
using CommunityToolkit.Mvvm.Messaging;
using Microsoft.UI.Windowing;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using System;
using System.Diagnostics;
using System.Threading.Tasks;

// To learn more about WinUI, the WinUI project structure,
// and more about our project templates, see: http://aka.ms/winui-project-info.

namespace AdvancedBudgetManager.view.window {
    /// <summary>
    /// An empty window that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class ResetPasswordWindow : Window, IRecipient<GenericResultMessage> {
        private TaskCompletionSource<bool> taskCompletionSource = new();
        private ResetPasswordViewModel resetPasswordViewModel;
        private InputDataValidator inputValidator;
        private readonly int minimumPasswordLength;

        public ResetPasswordWindow(ResetPasswordViewModel resetPasswordViewModel) {
            AppWindow appWindow = this.AppWindow;
            appWindow.Resize(new Windows.Graphics.SizeInt32(500, 500));

            this.resetPasswordViewModel = resetPasswordViewModel;
            this.inputValidator = new InputDataValidator();
            this.minimumPasswordLength = 12;

            this.InitializeComponent();
            this.Closed += (_, _) => taskCompletionSource.TrySetResult(false);

            WeakReferenceMessenger.Default.Register<GenericResultMessage>(this);
        }

        public Task<bool> ShowModalAsync(Window parentWindow) {
            WinRT.Interop.WindowNative.GetWindowHandle(parentWindow);


            this.Activate();
            return taskCompletionSource.Task;
        }

        public async void ResetPasswordButton_Click(object sender, RoutedEventArgs e) {
            PasswordSecurityManager passwordSecurityManager = new PasswordSecurityManager();

            ContentDialog passwordResetErrorDialog = new ContentDialog {
                Title = "Reset password",
                CloseButtonText = "OK",
                XamlRoot = this.Content.XamlRoot
            };

            if (inputValidator.IsEmpty(NewPasswordBox.Password) || inputValidator.IsEmpty(ConfirmPasswordBox.Password)) {
                passwordResetErrorDialog.Content = "Please fill in all the required fields!";
                await passwordResetErrorDialog.ShowAsync();

                return;
            }

            if (!inputValidator.IsMatch(NewPasswordBox.Password, ConfirmPasswordBox.Password)) {
                passwordResetErrorDialog.Content = "The passwords don't match! Please try again.";
                await passwordResetErrorDialog.ShowAsync();

                return;
            }

            if (!inputValidator.HasRequiredLength(NewPasswordBox.Password, minimumPasswordLength, ComparisonMode.LENIENT)) {
                passwordResetErrorDialog.Content = $"Your password should be at least {minimumPasswordLength} characters long! Please try again.";
                await passwordResetErrorDialog.ShowAsync();

                return;
            }

            if (!inputValidator.IsValidPassword(NewPasswordBox.Password)) {
                passwordResetErrorDialog.Content = "Invalid password! Your password must contain:\n1.Lowercase and uppercase letters (a-zA-z) \n2.Digits (0-9) \n3.Special characters (@#$%<>?)";
                await passwordResetErrorDialog.ShowAsync();

                return;
            }


            NewPasswordBox.Password = String.Empty;
            ConfirmPasswordBox.Password = String.Empty;

            //Triggers the reset password command from the ViewModel (generated by the [RelayCommand] annotation)
            resetPasswordViewModel.ResetPasswordCommand.Execute(null);

        }

        public void CancelButton_Click(object sender, RoutedEventArgs e) {
            taskCompletionSource.TrySetResult(false);
            this.Close();
        }

        public async void Receive(GenericResultMessage message) {
            ContentDialog passwordResetContentDialog = new ContentDialog {
                Title = "Password reset",
                Content = message.Message,
                PrimaryButtonText = "OK",
                XamlRoot = this.Content.XamlRoot
            };

            ContentDialogResult displayResult = await passwordResetContentDialog.ShowAsync();

            if (displayResult == ContentDialogResult.Primary && message.IsSuccess) {
                Debug.WriteLine("Closing the password reset window...");
                this.Close();
            }
        }
    }
}
